apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dreamvo
  name: dreamvo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dreamvo
  template:
    metadata:
      labels:
        app: dreamvo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: dreamvo/website@sha256:a74b9b7e9b0f93ad5aed88b39855d18c86973ad93341a68ef2765ee87a5bc2a0
          name: dreamvo
          imagePullPolicy: Always
          args:
            - start
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
