apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dreamvo
  name: dreamvo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dreamvo
  template:
    metadata:
      labels:
        app: dreamvo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: dreamvo/website@sha256:e3565df1f5cfa9f9579e73b1df8e794384eb08ea45778214b5b6025f5cd114bd
          name: dreamvo
          imagePullPolicy: Always
          args:
            - start
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
